/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(AppendPrefix.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(9d1d3e1bfdc142646684dfc5bc67c1e8)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <LibreLoRa/AppendPrefix.h>
// pydoc.h is automatically generated in the build directory
#include <AppendPrefix_pydoc.h>

void bind_AppendPrefix(py::module& m)
{

    using AppendPrefix    = gr::LibreLoRa::AppendPrefix;


    py::class_<AppendPrefix,
               gr::block,
               gr::basic_block,
	       std::shared_ptr<AppendPrefix>>(m, "AppendPrefix", D(AppendPrefix))

        .def(py::init(&AppendPrefix::make),
           py::arg("SF"),
           py::arg("symbolSize"),
           py::arg("nUpchirps"),
           py::arg("syncWordNumber"),
           D(AppendPrefix,make)
        )
        



        ;




}








