/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(AppendSilence.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(6bce9e74ee33b54f670d1df6bbd0d31b)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <LibreLoRa/AppendSilence.h>
// pydoc.h is automatically generated in the build directory
#include <AppendSilence_pydoc.h>

void bind_AppendSilence(py::module& m)
{

    using AppendSilence    = gr::LibreLoRa::AppendSilence;


    py::class_<AppendSilence,
               gr::block,
               gr::basic_block,
	       std::shared_ptr<AppendSilence>>(m, "AppendSilence", D(AppendSilence))

        .def(py::init(&AppendSilence::make),
           D(AppendSilence,make)
        )
        



        ;




}








