/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(BytesToNibbles.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(8023887e4b2827dd407c1e0545f891a7)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <LibreLoRa/BytesToNibbles.h>
// pydoc.h is automatically generated in the build directory
#include <BytesToNibbles_pydoc.h>

void bind_BytesToNibbles(py::module& m)
{

    using BytesToNibbles    = gr::LibreLoRa::BytesToNibbles;


    py::class_<BytesToNibbles,
	       gr::sync_interpolator,
	       gr::sync_block,
               gr::block,
               gr::basic_block,
	       std::shared_ptr<BytesToNibbles>>(m, "BytesToNibbles", D(BytesToNibbles))

        .def(py::init(&BytesToNibbles::make),
           D(BytesToNibbles,make)
        )
        



        ;




}








