/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(chirpSelect.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c8a2d11106ab7bc6a52a21c4b06c2dcf)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <LibreLoRa/chirpSelect.h>
// pydoc.h is automatically generated in the build directory
#include <chirpSelect_pydoc.h>

void bind_chirpSelect(py::module& m)
{

    using chirpSelect    = gr::LibreLoRa::chirpSelect;


    py::class_<chirpSelect,
	       gr::sync_block,
               gr::block,
               gr::basic_block,
	       std::shared_ptr<chirpSelect>>(m, "chirpSelect", D(chirpSelect))

        .def(py::init(&chirpSelect::make),
           py::arg("SF"),
           py::arg("symbolSize"),
           D(chirpSelect,make)
        )
        



        ;




}








