/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(convolution.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(3d2f4ed81c7e02027b38d053c9c4f756)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <LibreLoRa/convolution.h>
// pydoc.h is automatically generated in the build directory
#include <convolution_pydoc.h>

void bind_convolution(py::module& m)
{

    using convolution    = gr::LibreLoRa::convolution;


    py::class_<convolution,
	       gr::sync_block,
               gr::block,
               gr::basic_block,
	       std::shared_ptr<convolution>>(m, "convolution", D(convolution))

        .def(py::init(&convolution::make),
           py::arg("window"),
           D(convolution,make)
        )
        



        ;




}








