/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(Correlation.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(0185c7d70f3589b34de149540d51acc1)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <LibreLoRa/Correlation.h>
// pydoc.h is automatically generated in the build directory
#include <Correlation_pydoc.h>

template<typename T>
void bind_Correlation_template(py::module& m, const char* classname)
{

    using Correlation    = gr::LibreLoRa::Correlation<T>;


    py::class_<Correlation,
	       gr::sync_block,
               gr::block,
               gr::basic_block,
	       std::shared_ptr<Correlation>>(m, classname, D(Correlation))

        .def(py::init(&Correlation::make),
           py::arg("symbol"),
           D(Correlation,make)
        );
}

void bind_Correlation(py::module& m)
{
    bind_Correlation_template<float>(m, "Correlation_ff");
    bind_Correlation_template<gr_complex>(m, "Correlation_cc");
}



