/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(Encode.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(1405dafb5061e3cbbaa3406069d5f284)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <LibreLoRa/Encode.h>
// pydoc.h is automatically generated in the build directory
#include <Encode_pydoc.h>

void bind_Encode(py::module& m)
{

    using Encode    = gr::LibreLoRa::Encode;


    py::class_<Encode,
	       gr::sync_block,
               gr::block,
               gr::basic_block,
	       std::shared_ptr<Encode>>(m, "Encode", D(Encode))

        .def(py::init(&Encode::make),
           py::arg("CR"),
           D(Encode,make)
        )
        



        ;




}








