/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(FFTMax.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(8a8ed3697a9e96fb62838d78e3d2359a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <LibreLoRa/FFTMax.h>
// pydoc.h is automatically generated in the build directory
#include <FFTMax_pydoc.h>

void bind_FFTMax(py::module& m)
{

    using FFTMax    = gr::LibreLoRa::FFTMax;


    py::class_<FFTMax,
	       gr::sync_block,
               gr::block,
               gr::basic_block,
	       std::shared_ptr<FFTMax>>(m, "FFTMax", D(FFTMax))

        .def(py::init(&FFTMax::make),
           py::arg("DFTSize"),
           py::arg("window"),
           D(FFTMax,make)
        )
        



        ;




}








