/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(frequencyTrackerNLMS.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(8ee5c9c3439e8861328e2382f2eb3eb7)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <LibreLoRa/frequencyTrackerNLMS.h>
// pydoc.h is automatically generated in the build directory
#include <frequencyTrackerNLMS_pydoc.h>

void bind_frequencyTrackerNLMS(py::module& m)
{

    using frequencyTrackerNLMS    = gr::LibreLoRa::frequencyTrackerNLMS;


    py::class_<frequencyTrackerNLMS,
	       gr::sync_block,
               gr::block,
               gr::basic_block,
	       std::shared_ptr<frequencyTrackerNLMS>>(m, "frequencyTrackerNLMS", D(frequencyTrackerNLMS))

        .def(py::init(&frequencyTrackerNLMS::make),
           py::arg("mu"),
           py::arg("window"),
           D(frequencyTrackerNLMS,make)
        )
        



        ;




}








