/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(frequencyTrackerN.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(8ba89d0bd77310ca12fdf0c18b68ed10)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <LibreLoRa/frequencyTrackerN.h>
// pydoc.h is automatically generated in the build directory
#include <frequencyTrackerN_pydoc.h>

template<typename T>
void bind_frequencyTrackerN_template(py::module& m, const char* classname)
{

    using frequencyTrackerN    = gr::LibreLoRa::frequencyTrackerN<T>;


    py::class_<frequencyTrackerN,
	       gr::sync_block,
               gr::block,
               gr::basic_block,
	       std::shared_ptr<frequencyTrackerN>>(m, classname, D(frequencyTrackerN))

        .def(py::init(&frequencyTrackerN::make),
           py::arg("mu"),
           py::arg("SF"),
           py::arg("OSF"),
           py::arg("window"),
           D(frequencyTrackerN,make)
        )
        



        ;




}

void bind_frequencyTrackerN(py::module& m)
{
    bind_frequencyTrackerN_template<float>(m, "frequencyTrackerN_ff");
    bind_frequencyTrackerN_template<gr_complex>(m, "frequencyTrackerN_cc");
}





