/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(grayEncode.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(072759be01aebd424ba37c32e7e780cb)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <LibreLoRa/grayEncode.h>
// pydoc.h is automatically generated in the build directory
#include <grayEncode_pydoc.h>

void bind_grayEncode(py::module& m)
{

    using grayEncode    = gr::LibreLoRa::grayEncode;


    py::class_<grayEncode,
	       gr::sync_block,
               gr::block,
               gr::basic_block,
	       std::shared_ptr<grayEncode>>(m, "grayEncode", D(grayEncode))

        .def(py::init(&grayEncode::make),
           py::arg("SF"),
           D(grayEncode,make)
        )
        



        ;




}








