/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(hier_test2.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(59486422dbabb970997bbfda9ec23440)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <LibreLoRa/hier_test2.h>
// pydoc.h is automatically generated in the build directory
#include <hier_test2_pydoc.h>

void bind_hier_test2(py::module& m)
{

    using hier_test2    = gr::LibreLoRa::hier_test2;


    py::class_<hier_test2,
        std::shared_ptr<hier_test2>>(m, "hier_test2", D(hier_test2))

        .def(py::init(&hier_test2::make),
           py::arg("SF"),
           py::arg("OSF"),
           py::arg("nUpchirps"),
           py::arg("syncWordNumber"),
           py::arg("minCorr"),
           py::arg("corrStop"),
           D(hier_test2,make)
        )
        



        ;




}








