/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(Interleave.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(bea9268f528ee12998a9bf4b56566bc4)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <LibreLoRa/Interleave.h>
// pydoc.h is automatically generated in the build directory
#include <Interleave_pydoc.h>

void bind_Interleave(py::module& m)
{

    using Interleave    = gr::LibreLoRa::Interleave;


    py::class_<Interleave,
               gr::block,
               gr::basic_block,
	       std::shared_ptr<Interleave>>(m, "Interleave", D(Interleave))

        .def(py::init(&Interleave::make),
           py::arg("SF"),
           py::arg("CR"),
           D(Interleave,make)
        )
        



        ;




}








