/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(LoRaPDUHeaderGenerator.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(9d3a0607256f6a3f98677ac0f9539932)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <LibreLoRa/LoRaPDUHeaderGenerator.h>
// pydoc.h is automatically generated in the build directory
#include <LoRaPDUHeaderGenerator_pydoc.h>

void bind_LoRaPDUHeaderGenerator(py::module& m)
{

    using LoRaPDUHeaderGenerator    = gr::LibreLoRa::LoRaPDUHeaderGenerator;


    py::class_<LoRaPDUHeaderGenerator,
	       gr::tagged_stream_block,
               gr::block,
               gr::basic_block,
        std::shared_ptr<LoRaPDUHeaderGenerator>>(m, "LoRaPDUHeaderGenerator", D(LoRaPDUHeaderGenerator))

        .def(py::init(&LoRaPDUHeaderGenerator::make),
           py::arg("lengthTagName"),
           D(LoRaPDUHeaderGenerator,make)
        )
        



        ;




}








