/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(LoRaPDUHeaderReader.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(e7ad8d57077f30e1bd7f54e87e746ade)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <LibreLoRa/LoRaPDUHeaderReader.h>
// pydoc.h is automatically generated in the build directory
#include <LoRaPDUHeaderReader_pydoc.h>

void bind_LoRaPDUHeaderReader(py::module& m)
{

    using LoRaPDUHeaderReader    = gr::LibreLoRa::LoRaPDUHeaderReader;


    py::class_<LoRaPDUHeaderReader,
	       gr::tagged_stream_block,
               gr::block,
               gr::basic_block,
	       std::shared_ptr<LoRaPDUHeaderReader>>(m, "LoRaPDUHeaderReader", D(LoRaPDUHeaderReader))

        .def(py::init(&LoRaPDUHeaderReader::make),
           py::arg("lengthTagName"),
           D(LoRaPDUHeaderReader,make)
        )
        



        ;




}








