/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(NibblesToBytes.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(530f18bbd09dd2bd79948cbe95bbff0c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <LibreLoRa/NibblesToBytes.h>
// pydoc.h is automatically generated in the build directory
#include <NibblesToBytes_pydoc.h>

void bind_NibblesToBytes(py::module& m)
{

    using NibblesToBytes    = gr::LibreLoRa::NibblesToBytes;


    py::class_<NibblesToBytes,
	       gr::sync_decimator,
	       gr::sync_block,
               gr::block,
               gr::basic_block,
	       std::shared_ptr<NibblesToBytes>>(m, "NibblesToBytes", D(NibblesToBytes))
      
        .def(py::init(&NibblesToBytes::make),
           D(NibblesToBytes,make)
        )
        



        ;




}








