/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(PowerDetector.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(22e0849fd84bffd550c4faa30b5c4f31)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <LibreLoRa/PowerDetector.h>
// pydoc.h is automatically generated in the build directory
#include <PowerDetector_pydoc.h>

void bind_PowerDetector(py::module& m)
{

    using PowerDetector    = gr::LibreLoRa::PowerDetector;


    py::class_<PowerDetector,
               gr::block,
               gr::basic_block,
	       std::shared_ptr<PowerDetector>>(m, "PowerDetector", D(PowerDetector))

        .def(py::init(&PowerDetector::make),
           py::arg("sampRate"),
           py::arg("threshold"),
           py::arg("timeoutSeconds"),
           py::arg("decimation"),
           py::arg("message"),
           D(PowerDetector,make)
        )
        



        ;




}








