/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(preambleDetector.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(42dbc87dfbe50507398e0a2696ccf1ce)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <LibreLoRa/preambleDetector.h>
// pydoc.h is automatically generated in the build directory
#include <preambleDetector_pydoc.h>

void bind_preambleDetector(py::module& m)
{

    using preambleDetector    = gr::LibreLoRa::preambleDetector;


    py::class_<preambleDetector,
               gr::hier_block2,
               gr::basic_block,
        std::shared_ptr<preambleDetector>>(m, "preambleDetector", D(preambleDetector))

        .def(py::init(&preambleDetector::make),
           py::arg("SF"),
           py::arg("OSF"),
           py::arg("nUpchirps"),
           py::arg("syncWordNumber"),
           D(preambleDetector,make)
        )
        



        ;




}








