/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(randomize.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c341dc9c48088dcb406be47a5a38a181)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <LibreLoRa/randomize.h>
// pydoc.h is automatically generated in the build directory
#include <randomize_pydoc.h>

void bind_randomize(py::module& m)
{

    using randomize    = gr::LibreLoRa::randomize;


    py::class_<randomize,
	       gr::sync_block,
               gr::block,
               gr::basic_block,
	       std::shared_ptr<randomize>>(m, "randomize", D(randomize))

        .def(py::init(&randomize::make),
           py::arg("lfsrInitialState") =  0xff,
           py::arg("payloadSize") =  0,
           D(randomize,make)
        )
        



        ;




}








