/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(Remainder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(9f5db398dc48484dae6f8dd436866a48)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <LibreLoRa/Remainder.h>
// pydoc.h is automatically generated in the build directory
#include <Remainder_pydoc.h>

void bind_Remainder(py::module& m)
{

    using Remainder    = gr::LibreLoRa::Remainder;


    py::class_<Remainder,
	       gr::sync_block,
               gr::block,
               gr::basic_block,
	       std::shared_ptr<Remainder>>(m, "Remainder", D(Remainder))

        .def(py::init(&Remainder::make),
           py::arg("divisor"),
           D(Remainder,make)
        )
        



        ;




}








