/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(SelectMax.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(6391269a5d466e3634a8bde93af8694e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <LibreLoRa/SelectMax.h>
// pydoc.h is automatically generated in the build directory
#include <SelectMax_pydoc.h>

void bind_SelectMax(py::module& m)
{

    using SelectMax    = gr::LibreLoRa::SelectMax;


    py::class_<SelectMax,
	       gr::sync_block,
               gr::block,
               gr::basic_block,
	       std::shared_ptr<SelectMax>>(m, "SelectMax", D(SelectMax))

        .def(py::init(&SelectMax::make),
           py::arg("nInputs"),
           D(SelectMax,make)
        )
        



        ;




}








