/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(slidingDFT.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(8460996806c445ade270034c89d77816)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <LibreLoRa/slidingDFT.h>
// pydoc.h is automatically generated in the build directory
#include <slidingDFT_pydoc.h>

void bind_slidingDFT(py::module& m)
{

    using slidingDFT    = gr::LibreLoRa::slidingDFT;


    py::class_<slidingDFT,
	       gr::sync_block,
               gr::block,
               gr::basic_block,
	       std::shared_ptr<slidingDFT>>(m, "slidingDFT", D(slidingDFT))

        .def(py::init(&slidingDFT::make),
           py::arg("DFTLength"),
           py::arg("windowSize"),
           D(slidingDFT,make)
        )
        



        ;




}








