/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(streamToHistoryVector.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(e0af6ecc6065cab7fd5d4415f9836ef1)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <LibreLoRa/streamToHistoryVector.h>
// pydoc.h is automatically generated in the build directory
#include <streamToHistoryVector_pydoc.h>

template<typename T>
void bind_streamToHistoryVector_template(py::module& m, const char* classname)
{

    using streamToHistoryVector    = gr::LibreLoRa::streamToHistoryVector<T>;


    py::class_<streamToHistoryVector,
	       gr::sync_decimator,
	       gr::sync_block,
               gr::block,
               gr::basic_block,
        std::shared_ptr<streamToHistoryVector>>(m, classname, D(streamToHistoryVector))

        .def(py::init(&streamToHistoryVector::make),
           py::arg("nVect"),
           py::arg("decimation"),
           D(streamToHistoryVector,make)
        )
        



        ;




}

void bind_streamToHistoryVector(py::module& m)
{
    bind_streamToHistoryVector_template<float>(m, "streamToHistoryVector_ff");
    bind_streamToHistoryVector_template<gr_complex>(m, "streamToHistoryVector_cc");
}






