/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(SymbolMod.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(10004bfbe26f231269f7dbbe673f53f7)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <LibreLoRa/SymbolMod.h>
// pydoc.h is automatically generated in the build directory
#include <SymbolMod_pydoc.h>

void bind_SymbolMod(py::module& m)
{

    using SymbolMod    = gr::LibreLoRa::SymbolMod;


    py::class_<SymbolMod,
	       gr::sync_interpolator,
	       gr::sync_block,
               gr::block,
               gr::basic_block,
	       std::shared_ptr<SymbolMod>>(m, "SymbolMod", D(SymbolMod))

        .def(py::init(&SymbolMod::make),
           py::arg("SF"),
           py::arg("symbolSize"),
           D(SymbolMod,make)
        )
        



        ;




}








