/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ToneDetector.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(a202a393d52ba360fdd02c71777be2c4)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <LibreLoRa/ToneDetector.h>
// pydoc.h is automatically generated in the build directory
#include <ToneDetector_pydoc.h>

void bind_ToneDetector(py::module& m)
{

    using ToneDetector    = gr::LibreLoRa::ToneDetector;


    py::class_<ToneDetector,
	       gr::sync_block,
               gr::block,
               gr::basic_block,
	       std::shared_ptr<ToneDetector>>(m, "ToneDetector", D(ToneDetector))

        .def(py::init(&ToneDetector::make),
           py::arg("DFTSize"),
           D(ToneDetector,make)
        )
        



        ;




}








