/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(TransmitterController.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ff713988e5c6bfbb5b3d6826355fdf7d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <LibreLoRa/TransmitterController.h>
// pydoc.h is automatically generated in the build directory
#include <TransmitterController_pydoc.h>

void bind_TransmitterController(py::module& m)
{

    using TransmitterController    = gr::LibreLoRa::TransmitterController;


    py::class_<TransmitterController,
               gr::block,
               gr::basic_block,
	       std::shared_ptr<TransmitterController>>(m, "TransmitterController", D(TransmitterController))

        .def(py::init(&TransmitterController::make),
           py::arg("SF"),
           py::arg("symbolSize"),
           py::arg("CR"),
           py::arg("payloadSize"),
           py::arg("CRCpresent"),
           py::arg("lowDataRate"),
           D(TransmitterController,make)
        )
        



        ;




}








